/**
 * File auto-generated by AS3 AssetsParser
 * NemoStein, 2012
 * http://www.nemostein.com.br
 */
package nemostein.games.botmayhem.assets.arenas.greenish
{
	import flash.display.Bitmap;
	
	[Embed(source="greenish.png")]
	
	public class AssetArenasGreenishGreenish extends Bitmap
	{
	
	}
}