/**
 * File auto-generated by AS3 AssetsParser
 * NemoStein, 2012
 * http://www.nemostein.com.br
 */
package nemostein.games.botmayhem.assets.hud
{
	import flash.display.Bitmap;
	
	[Embed(source="redBarStart.png")]
	
	public class AssetRedBarStart extends Bitmap
	{
	
	}
}