/**
 * File auto-generated by AS3 AssetsParser
 * NemoStein, 2012
 * http://www.nemostein.com.br
 */
package nemostein.games.botmayhem.assets.particles
{
	import flash.display.Bitmap;
	
	[Embed(source="smoke1.png")]
	
	public class AssetParticlesSmoke1 extends Bitmap
	{
	
	}
}