/**
 * File auto-generated by AS3 AssetsParser
 * NemoStein, 2012
 * http://www.nemostein.com.br
 */
package nemostein.games.botmayhem.assets.menu
{
	import flash.display.Bitmap;
	
	[Embed(source="developerShadow.png")]
	
	public class AssetMenuDeveloperShadow extends Bitmap
	{
	
	}
}