/**
 * File auto-generated by AS3 AssetsParser
 * NemoStein, 2012
 * http://www.nemostein.com.br
 */
package nemostein.games.botmayhem.assets
{
	import flash.display.Bitmap;
	
	[Embed(source="OverlayScreen.png")]
	
	public class AssetOverlayScreen extends Bitmap
	{
	
	}
}