/**
 * File auto-generated by AS3 AssetsParser
 * NemoStein, 2012
 * http://www.nemostein.com.br
 */
package nemostein.games.botmayhem.assets.bots.hero
{
	import flash.display.Bitmap;
	
	[Embed(source="heroSpritesheet.png")]
	
	public class AssetBotsHeroHeroSpritesheet extends Bitmap
	{
	
	}
}