/**
 * File auto-generated by AS3 AssetsParser
 * NemoStein, 2012
 * http://www.nemostein.com.br
 */
package nemostein.games.botmayhem.assets.cursors
{
	import flash.display.Bitmap;
	
	[Embed(source="aim_b.png")]
	
	public class AssetAimB extends Bitmap
	{
	
	}
}