/**
 * File auto-generated by AS3 AssetsParser
 * NemoStein, 2012
 * http://www.nemostein.com.br
 */
package nemostein.games.botmayhem.assets.iris
{
	import flash.display.Bitmap;
	
	[Embed(source="iris02.png")]
	
	public class AssetIris02 extends Bitmap
	{
	
	}
}