/**
 * File auto-generated by AS3 AssetsParser
 * NemoStein, 2012
 * http://www.nemostein.com.br
 */
package nemostein.games.botmayhem.assets.decals
{
	import flash.display.Bitmap;
	
	[Embed(source="scorchE.png")]
	
	public class AssetScorchE extends Bitmap
	{
	
	}
}