/**
 * File auto-generated by AS3 AssetsParser
 * NemoStein, 2012
 * http://www.nemostein.com.br
 */
package nemostein.games.botmayhem.assets.weaponry.bullets
{
	import flash.display.Bitmap;
	
	[Embed(source="simpleBullet.png")]
	
	public class AssetSimpleBullet extends Bitmap
	{
	
	}
}